/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgrrustudentmanagement;

import javax.swing.JOptionPane;

/**
 *
 * @author PANKU
 */
public class GetReportFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form GetReportFrame
     */
    public GetReportFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGet = new javax.swing.JButton();
        cboCourse = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Get Excel Report");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/xls_icon.png"))); // NOI18N

        btnGet.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnGet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/xls_icon.png"))); // NOI18N
        btnGet.setText("Get Report");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });

        cboCourse.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        cboCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Sc. IT", "BCA", "BBA", "B.Pharma", "MCA", "MBA", "M.Pharma", "Ph.D" }));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        jLabel1.setText("   Export Report to Excel Sheet");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnGet, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(cboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnGet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
       String Course = ""+cboCourse.getSelectedItem();
       String s = ("E://"+Course+"_Data"+".xls");
        boolean status = MysqlToXls.getXLS(Course);
        if(status==true){
            JOptionPane.showMessageDialog(this, "Record has been saved to Location: "+s, "Record Saved to Excel Sheet!", JOptionPane.INFORMATION_MESSAGE);
            //resetForm();
        }else{
            JOptionPane.showMessageDialog(this, "Record has NOT been saved", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGet;
    private javax.swing.JComboBox<String> cboCourse;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
