/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgrrustudentmanagement;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PANKU
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        String userName = System.getProperty("user");
        String roleName = System.getProperty("role");
        //setTitle("SGRR University: Stuent Management System... Welcome "+userName+" ("+roleName+")");
        
        switch(roleName){
            case "admin":
                break;
            default:
                jMenuItem4.setVisible(false);
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGetReport = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuSubmitFee = new javax.swing.JMenuItem();
        mnuPrintFee = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGRR University : Student Management System");
        setIconImages(null);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/SGRR-University-Logo-1.jpg"))); // NOI18N
        jMenu5.setText("SGRR University");
        jMenu5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jMenuBar1.add(jMenu5);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/student-icon-53587.png"))); // NOI18N
        jMenu1.setText("Student ");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/add_icon.png"))); // NOI18N
        jMenuItem1.setText("Add Student");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/manage_icon.png"))); // NOI18N
        jMenuItem2.setText("Manage Student");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/search_icon.png"))); // NOI18N
        jMenuItem3.setText("Search Student");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/course-icon.png"))); // NOI18N
        jMenu2.setText("Course ");
        jMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        mnuGetReport.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuGetReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/xls_icon.png"))); // NOI18N
        mnuGetReport.setText("Get Report");
        mnuGetReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGetReportActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGetReport);

        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/search.png"))); // NOI18N
        jMenuItem6.setText("Search");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/fee_icon.png"))); // NOI18N
        jMenu3.setText("Fees ");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        mnuSubmitFee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuSubmitFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/feesubmit_icon.jpg"))); // NOI18N
        mnuSubmitFee.setText("Submit Fees");
        mnuSubmitFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSubmitFeeActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSubmitFee);

        mnuPrintFee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuPrintFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/print_icon_menu1.png"))); // NOI18N
        mnuPrintFee.setText("Print Reciept");
        mnuPrintFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPrintFeeActionPerformed(evt);
            }
        });
        jMenu3.add(mnuPrintFee);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/users_icon.png"))); // NOI18N
        jMenu4.setText("User ");
        jMenu4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jMenuItem4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/add_icon.png"))); // NOI18N
        jMenuItem4.setText("Add User");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/manage_icon.png"))); // NOI18N
        jMenuItem5.setText("Change Password");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/about_icon.png"))); // NOI18N
        jMenu6.setText("About ");
        jMenu6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        mnuAbout.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/me_icon.png"))); // NOI18N
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        jMenu6.add(mnuAbout);

        mnuHelp.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        mnuHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sgrrustudentmanagement/help_icon.png"))); // NOI18N
        mnuHelp.setText("Help");
        mnuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHelpActionPerformed(evt);
            }
        });
        jMenu6.add(mnuHelp);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AddStudentFrame f = new AddStudentFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ManageStudentFrame f = new ManageStudentFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuSubmitFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSubmitFeeActionPerformed
        FeeSubmitFrame f = new FeeSubmitFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_mnuSubmitFeeActionPerformed

    private void mnuPrintFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPrintFeeActionPerformed
        FeePrintFrame f = new FeePrintFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_mnuPrintFeeActionPerformed

    private void mnuGetReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGetReportActionPerformed
        GetReportFrame f = new GetReportFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_mnuGetReportActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        AboutFrame f = new AboutFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_mnuAboutActionPerformed

    private void mnuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuHelpActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SearchStudentFrame f = new SearchStudentFrame();
         jDesktopPane1.add(f);
         try {
            f.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       SearchCourseFrame f = new SearchCourseFrame();
         jDesktopPane1.add(f);
        try {
            f.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         ChangePasswordFrame f = new ChangePasswordFrame();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         AddUser f = new AddUser();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JMenuItem mnuGetReport;
    private javax.swing.JMenuItem mnuHelp;
    private javax.swing.JMenuItem mnuPrintFee;
    private javax.swing.JMenuItem mnuSubmitFee;
    // End of variables declaration//GEN-END:variables
}
